MOVIELIST_COL_TITLE = 0
MOVIELIST_COL_YEAR = 1
MOVIELIST_COL_RATING = 2
MOVIELIST_COL_FAVOURITE = 3
MOVIELIST_COL_WATCHLATER = 4

NAME_USER_LIST_WATCHLATER = 'watchlater'
NAME_USER_LIST_FAVOURITES = 'favourites'
